apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-application
  template:
    metadata:
      labels:
        app: java-application
    spec:
      containers:
        - name: java-application
          image: 008971659622.dkr.ecr.us-west-2.amazonaws.com/test-eks
          ports:
            - containerPort: 8080