apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: k8s-final
          image: https://87060C97EBF146FA438D9E0335EA8300.gr7.us-west-2.eks.amazonaws.com
          ports:
            - containerPort: 8080
